# Generated by Django 3.2.8 on 2021-11-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20211021_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='txtEmail',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
