# Generated by Django 3.2.8 on 2021-11-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contact_txtemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='txtEmail',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
