# Generated by Django 3.2.8 on 2021-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_contact_txtemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='txtPhone',
            field=models.TextField(),
        ),
    ]
